# Generated by Django 3.1.4 on 2021-01-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteName', models.CharField(max_length=10)),
                ('about', models.CharField(max_length=25)),
                ('teachers', models.CharField(max_length=20)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
    ]
