# Generated by Django 3.1.4 on 2021-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notebook_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='content',
            field=models.TextField(default='CONTENT'),
            preserve_default=False,
        ),
    ]
