# Generated by Django 3.1.4 on 2021-01-20 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notebook_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='lastDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
