# Generated by Django 3.1.7 on 2021-04-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_notebook_lastdatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('password', models.TextField()),
            ],
        ),
    ]
