# Generated by Django 3.1.7 on 2021-04-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_usersdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='bookOwner',
            field=models.CharField(default='MAIL', max_length=20),
            preserve_default=False,
        ),
    ]
