# Generated by Django 3.2.3 on 2021-05-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_notebook_bookowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='mail',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
