# Generated by Django 3.2.3 on 2021-06-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210531_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupTempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=25)),
                ('password', models.TextField()),
            ],
        ),
    ]
