# Generated by Django 3.2.3 on 2021-06-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_signuptempdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
