# Generated by Django 4.0 on 2022-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_notebook_id_notebook_sharelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='shareList',
            field=models.JSONField(),
        ),
    ]
