# Generated by Django 4.0 on 2022-01-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_notebook_sharelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='shareList',
            field=models.JSONField(null=True),
        ),
    ]
