# Generated by Django 4.0.6 on 2022-07-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_notebook_sharelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='authKey',
            field=models.CharField(default='VYWZUQ660X', max_length=35),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='isTwoFactorEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
