# Generated by Django 4.2 on 2023-04-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_usersdata_authkey_usersdata_istwofactorenabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='authKey',
            field=models.CharField(default='IX6IO81717', max_length=35),
        ),
    ]
